### ISSUE TITLE
Add end of the study questionnaire to the end of study phase

### ISSUE THREAD

**Issue by arielle68** [EmotionCognitionLab/pvs#337] opened 2023-01-26 21:52 UTC
Hi, 

The end of study questionnaire should be administered at the end of the Week 12 assessment.

Here is the link to its spec : https://docs.google.com/document/d/1-i38wwb_gafED-0INQ0-YVdq12Eef17_pVg0OHPlpEE/edit?usp=sharing

Thanks

**Comment by maramather** [comment] 2023-03-08 22:19
Let's put this into Qualtrics. Kaoru, would you ask a team member to use the spec linked above to create a Qualtrics questionnaire?

Noah, once we have a Qualtrics questionnaire, could you make sure they get routed to complete it at the end of the post-study assessment?

**Comment by noah10** [comment] 2023-03-08 22:22
Note to whoever is creating the qualtrics questionnaire: Please set it up to have an embedded data field named "huid". I'll use that to pass the human (7 character) user id. And yes, I'll set something up to forward users to the qualtrics link once they finish the post-study assessment.

**Comment by nashiro** [comment] 2023-03-08 22:39
Mara, could we ask Padideh?
@arielle68 would it be possible to create a Qualtrics questionnaire, as Mara and Noah request above?

**Comment by nashiro** [comment] 2023-03-08 22:58
Paul just told me:
"Hi Kaoru, I think Christine already created this on Qualtrics. It’s in Post-Study Questionnaire under Heartbeam study."
Qualtrics Link : https://usc.qualtrics.com/jfe/form/SV_40fyXTh4ErOBePc

Paul said he will set it up to have an embedded data field named "huid" as Noah requested.
Thanks Paul! @choipaul92 

Padideh, @arielle68 please disregard my request above.

**Comment by noah10** [comment] 2023-03-23 02:18
We won't be emailing it; we'll simply send people to it when they finish the final task in set 12. Which brings up a question: Do we want to show people the "You're all done" screen and have them click a button to go to the survey, or just have them get launched straight from the last image in pattern-separation-recall (which is the final task in set 12) to qualtrics?

**Comment by nashiro** [comment] 2023-03-23 02:37
If people see the "You're all done" screen, they may not complete the survey. Would it be possible to change the text to something like "Please click a button to complete the final task"?

Mara probably have a better suggestion. @maramather

**Comment by maramather** [comment] 2023-03-23 03:17
I like the option "have them get launched straight from the last image in pattern-separation-recall (which is the final task in set 12) to qualtrics". The end of the qualtrics study can tell them congratulations and thank them for completing the study.

**Comment by nashiro** [comment] 2023-03-23 14:45
Thanks Mara. Can you go with Mara's suggestion?

**Comment by noah10** [comment] 2023-03-23 21:39
OK - this is up on dev and ready to be tested. You can test it by going to https://dev.heartbeamstudy.org/daily-tasks/?tasks=pattern-separation-recall&setNum=12 . Note the following:

- I'm using the same qualtrics link on dev and prod, so if you fill out the survey on dev your answers will (presumably) be mingled with the answers from actual participants
- I didn't fill out the survey, so I don't know if it displays the "thanks and congratulations" message that Mara wanted users to see at the end

@nashiro I'm not sure who should test this, so I'm assigning it to you for now. Feel free to re-assign to someone else, of course.

**Comment by choipaul92** [comment] 2023-03-23 23:08
<img width="834" alt="Screen Shot 2023-03-23 at 4 06 02 PM" src="https://user-images.githubusercontent.com/89946691/227383911-ffc2a9f7-d013-4260-9824-8eeb1758ee0a.png">

Tested it out and looks good. After the last task (pattern separation task), the post survey questionnaire is given right away. It's important to note that the survey does not have any "forced requirements" so participants can leave it blank.

**Comment by cho890** [comment] 2023-03-24 00:17
I just tried to test this but was not taken to the end of study questionnaire.  After completing the pattern separation task, I saw the below screenshot:
![image](https://user-images.githubusercontent.com/109320017/227392060-d0b78f67-bbdb-43d3-a36e-a4a77c113e8a.png)

**Comment by noah10** [comment] 2023-03-24 00:26
@cho890 - I'm not 100% sure, but I think the reason you got that is because you already have a set-finished record for set 12 in dev. (Assuming that you're using the cho890 account there.) Shall I mess with your data so that it doesn't look like you've already finished set 12?

**Comment by cho890** [comment] 2023-03-24 00:29
I used the christine.cho account to test this, not the cho890.  I don't recall testing set 12 in dev, though I could be mistaken.  If that is the cause, then I don't see a problem with deleting it so I can test this open issue.

**Comment by maramather** [comment] 2023-03-24 00:53
Paul - could you make Q1-7 required?

**Comment by maramather** [comment] 2023-03-24 00:54
We need to do better on the completion congratulations message. Does Qualtrics allow us to put a graphic there?

**Comment by cho890** [comment] 2023-03-24 16:56
> 

The change from completing the pattern separation task to the survey is rather abrupt.  Should we add a transition in between these two or a message at the top of the survey? Also, for me, questions 1-8 require a response.  I cannot advance without answering these questions.  Do we want to force responses?

**Comment by maramather** [comment] 2023-03-24 17:52
I agree, a transition message would be good. @cho890 what do you think of "Amazing work! You have finished all of our study except for a few wrap-up questions. Please fill those out here now."

Yes, I would like to force response for Q1-7 where we will need to report those for the study to (hopefully) convince reviewers that the two conditions were similar.

**Comment by noah10** [comment] 2023-03-24 17:55
Does that message go at the top of the survey? If not, how do they get from the transition message to the survey?

**Comment by maramather** [comment] 2023-03-24 17:58
Yes, it should be possible to put the message at the top of the survey, where instructions would normally go. @choipaul92 let us know if not.

**Comment by cho890** [comment] 2023-03-24 18:10
We can add it to the top of the survey, and put the instructions below it.  I like the message you proposed, @maramather.  I made a few edits; would this work? "Amazing work! You have finished all of our study, and we are very interested to hear about your overall experience. Please fill out the short survey below to share your thoughts and feedback about the study."

**Comment by maramather** [comment] 2023-03-24 18:31
That sounds like they are done with the study and the survey is optional. It should not be optional - it is an important part of the study.

**Comment by cho890** [comment] 2023-03-24 22:26
@maramather Following up from our conversation, how does this sound?  "Amazing work! You are nearly finished with the study, and you have one final survey to complete.  Please fill out the short survey below to share your overall experience in the study.  We are very interested in your thoughts and feedback!"

**Comment by maramather** [comment] 2023-03-24 22:59
sounds great to me!

**Comment by cho890** [comment] 2023-03-25 02:47
@maramather @choipaul92 I modified the message at the beginning of the survey and added a congratulatory message at the end.  I think the congratulatory message could use one more sentence, perhaps about the final payment?  Please let me know what you think.

**Comment by maramather** [comment] 2023-03-25 17:42
Yes, I think the congratulatory message regarding the questionnaire should be followed by an overall study thank you message. Something like a new line and "And congratulations on completing the entire study! It is an impressive accomplishment and we thank you for your help in investigating how paced breathing may help accelerate learning. We will be mailing you the final compensation check for your participation soon."



Also, on the survey, please make 
"If the amount of effort changed over the course of the brain games and/or breathing practice, please explain how it changed:" 

and "In particular, which aspects of the brain games and/or breathing practice do you think you would be likely to continue to practice?"

optional questions (they should not have to fill these out to continue)

**Comment by cho890** [comment] 2023-03-28 00:26
@maramather Sure!  I've added your edits to the congratulatory message and made those 2 questions optional.

**Comment by choipaul92** [comment] 2023-03-28 00:49
![Screenshot 2023-03-27 at 5 42 09 PM](https://user-images.githubusercontent.com/89946691/228097581-558d9a40-c27f-443d-9f21-8b5da0919318.png)
![Screenshot 2023-03-27 at 5 44 45 PM](https://user-images.githubusercontent.com/89946691/228097865-aa66b1ba-9622-4984-b094-76d63461642b.png)

Just checked and all updates were in place (including Q1-7 being forced and the two questions above being optional as well)

**Comment by noah10** [comment] 2023-03-30 16:11
By "abrupt transition" do you mean that it just goes immediately from the final task to the survey? If so, the solution for that was to add the "Amazing work, you are nearly finished" message to the top of the survey - see https://github.com/EmotionCognitionLab/pvs/issues/337#issuecomment-1483201585 . @maramather , assuming that that's still the way you want it, are there any other changes needed here or should it be pushed to production?

**Comment by cho890** [comment] 2023-04-01 00:13
Correct, we have added the transition message to the top of the survey.  This issue can be closed.

**Comment by noah10** [comment] 2023-04-01 01:26
This has been deployed to production.

**Closed by noah10** 2023-04-01 01:26 UTC
Labels: needs testing
