### ISSUE TITLE
Verbal learning question

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#128] opened 2021-11-16 04:53 UTC
For verbal learning, I'm wondering whether if someone types in a word that they recall and then do NOT hit return but instead hit the 'stop' button if that last word will be recorded. It is not essential that this last word be recorded, but it would be helpful if it were.

**Comment by Floozutter** [comment] 2021-11-17 12:48
Good point! Currently, any lingering input on that field is not recorded if the user clicks the button without pressing enter. I'll change it so that if the value in the input field is not empty, it will be recorded when the user clicks the button to continue.

**Comment by Floozutter** [comment] 2021-11-17 13:01
Once #134 is up, any remaining text in the input field will be recorded once the user clicks the button to continue.

To verify this, look for the values of the `"response"` keys in trials with a `"trial_type"` of `"memory-field"` in verbal-learning data.

**Comment by noah10** [comment] 2021-11-17 17:05
#134 is now up and ready for testing.

**Comment by maramather** [comment] 2021-11-19 17:53
@choipaul would you be able to test if you enter text on the verbal learning task and don't press return but instead press the button to stop, does that last text get recorded?

**Comment by choipaul92** [comment] 2022-01-10 16:59
Just tested the verbal learning. For the first three trials, I typed and pressed stop: cabbage [1st trial] zebra [2nd trial] and truck [3rd trial]. For the last five trials, I did the same: truck, cabinet [furniture trial], celery [vegetable trial], boat [transportation trial], zebra [animal trial]

**Comment by noah10** [comment] 2022-01-10 23:13
Looks pretty close to what I see in the db. (Instead of truck I see:
 "cabbage",
   "squirrel",
   "onion",
   "celery",
   "spinach",
   "zebra",
   "giraffe",
   "boat",
   "truck", but that's clearly not a bug with this code. Everything else is as described, so pressing stop does save the text that's in the field.) Closing.

**Closed by noah10** 2022-01-10 23:13 UTC
Labels: needs testing
