### ISSUE TITLE
N-back instructions

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#105] opened 2021-11-09 17:32 UTC
The TOP instruction paragraph for the 1-back and 2-back need to be swapped.

here is what is in the 2-back that needs to go into the 1-back:

"In the second part of this task, your job is to press the space bar when the number on the screen is the same as the number immediately before the number currently on the screen."

**Comment by Floozutter** [comment] 2021-11-17 13:09
This may be a duplicate of #97, or a result of the incorrect fix from #103. Either way, #105 should have fixed this, hopefully.

![fixed-ti2a](https://user-images.githubusercontent.com/57658864/140965552-a62e846b-5acb-4553-a84a-49936bad6945.png)

**Closed** 2021-11-19 17:57 UTC
Labels: needs testing
