### ISSUE TITLE
Images in Face-Name Recognition Task

### ISSUE THREAD

**Issue by andyjkim628** [EmotionCognitionLab/pvs#35] opened 2021-09-02 00:05 UTC
Two of my RAs said that the images do not show up for this task. One of them mentioned they are using Safari browser.

**Comment by noah10** [comment] 2021-09-02 01:44
It works for me in Safari, so I'm going to need some more details. Can either of them get the images to *never* show up, or was it just a one-time thing? If they never show up, please send me the browser, browser version, os and os version that they're using, as well as info about whether they're doing this stand-alone or as part of the daily tasks. (If they're doing it as part of the daily tasks knowing what set they're on would also be helpful. If they're doing it stand-alone we should make sure they're not using a mobile device.) A screen shot of it not showing up might be useful, too.

**Comment by andyjkim628** [comment] 2021-09-02 16:51
<img width="1306" alt="Screen Shot 2021-08-30 at 5 53 14 PM" src="https://user-images.githubusercontent.com/89949090/131884692-2e290333-6986-44be-8c88-194d2bdbab53.png">

I have attached a screenshot of what they saw. They are saying it is a one-time thing. Today, when both of them tried, it worked fine. They were completing as part of daily tasks. I am assuming it was set 1 when they found the errors. These are the two systems they were working on.

Safari Version 14.1.2 (16611.3.10.1.6) and macOS Big Sur 11.5.2 (20G95)
Google Chrome Version 92.0.4515.159 (Official Build) (x86_64) & macOS catalina (version 10.15.5)

**Comment by noah10** [comment] 2021-09-02 17:52
OK - I was messing with all of the images at one point, so it's possible that their testing coincided with that. I'll keep this open until we hear back from Alex's RA about whether she can reproduce this problem and if not I'll close it. (Though of course we can re-open if the problem comes back at all.)

**Comment by noah10** [comment] 2021-09-02 18:30
Alex says that they're showing up for her RA now as well, so I'm going to close this.

**Closed by noah10** 2021-09-02 18:30 UTC
