### ISSUE TITLE
Remove the flanker task from set 3

### ISSUE THREAD

**Issue by arielle68** [EmotionCognitionLab/pvs#210] opened 2022-06-01 02:01 UTC
We currently administer the flanker task  every other day (on set 1, set3 and set 5). We will administer the flanker task only on set 1 and set 5 in the future

**Comment by choipaul92** [comment] 2022-11-09 21:16
I tested this (maybe someone can confirm) and Flanker showed up on Set 1,3 and 5.

**Comment by noah10** [comment] 2023-01-19 17:10
@arielle68 Could you please let us know if this is working as intended?

**Comment by noah10** [comment] 2023-01-26 22:42
Closing as out-of-date: The latest version of the specs at https://docs.google.com/spreadsheets/d/1hYrIFnyd5hMNr_vbmOjVXs6xhPQV7s32ixpF-W-D9Tk/edit?pli=1#gid=713375495 shows flanker as being back in set 3.

**Closed** 2023-01-26 22:43 UTC
Labels: needs testing
