### ISSUE TITLE
Remove flanker from the set 1 of pre and post  phases

### ISSUE THREAD

**Issue by arielle68** [EmotionCognitionLab/pvs#346] opened 2023-02-10 21:53 UTC
Please remove flanker task from set 1. From now on, flanker task must be administered only in set 3 and 5.

I updated the spec for flanker task to reflect this. 

Thanks

**Comment by maramather** [comment] 2023-02-11 02:42
does the first instance of flanker have any additional instructions compared with the later instances? If so, we should make sure that the set 3 Flanker has those instructions.

**Comment by arielle68** [comment] 2023-02-14 20:38
Yes. In addition to removing the first set, instructions for the first set should be shown at the beginning of set 3. Thanks Mara for noticing it.

**Comment by noah10** [comment] 2023-02-15 19:55
This is ready to be tested on dev. Note that to test it you will need either an account that has not done any cognitive baseline tasks or to delete all of the cognitive baseline data from an account that has done them.

**Comment by maramather** [comment] 2023-02-20 01:59
@arielle68 said she completed testing the changes for set 1 and 3. She still needs to test set 7. As there is a wave of 4 participants starting the assessments tomorrow, we will close this issue so Noah can deploy the changes. However, Padideh please do the testing for sets 7 asap and post a new Github issue if it is not functioning as intended (demographics should be at beginning, there should be no n-back or flanker tests).

**Closed** 2023-02-20 01:59 UTC
Labels: needs testing
