### ISSUE TITLE
Text edit on welcome screen of home tasks 

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#256] opened 2022-10-06 17:20 UTC
On the welcome screen of the weeklong home tasks (https://dev.heartbeamstudy.org/daily-tasks/), the first sentence reads:

"At both the start (now) and the end (six months from now)..."

and should be updated to 

"At both the start (now) and the end (three months from now)..."

**Comment by noah10** [comment] 2022-10-06 18:51
Dupe of #231.

**Closed by noah10** 2022-10-06 18:51 UTC
